### ISSUE TITLE
Add code to delete uploaded files and check if exists function

### ISSUE THREAD

**Issue by avs-code** [avs-code/PREM-Podium-race-E-manager#13]
1. function to check if file exists not is working:

```
if (file_exists($target_file))
{
echo "Sorry, file already exists.";
} 
```
1. Add code to delete (unlink) uploaded files and delete that database record asociated to file.
   Example here:
   http://sparkadsl.0lx.net/pruebas/?page=upload
   file upload.php

Code similar to:
$res=mysql_query("SELECT file FROM tbl_uploads WHERE id=".$_GET['remove_id']);
$row=mysql_fetch_array($res);
mysql_query("DELETE FROM tbl_uploads WHERE id=".$_GET['remove_id']);
unlink("uploads/".$row['file']);

**Comment by inguni** [comment]
About the file exists it should works now. We still need to add the others functions

**Comment by avs-code** [comment]
About nº1, it seems that message not is showing, message that you see when file exists is "successfully uploaded" (line 69 from code i think) and is created a entry in database. But in background you can see sorry file already exists. http://i.imgur.com/D4elmri.jpg
Its like 2 messages, one from php status upload and other from sql database entry. Fail the second, I think because database entry is added althoug file is already exists. In adition may be best show the two status message (php & sql) in the same place to see them well.

So:
ok: if file exists not upload again.

Not ok: entry is created in database.

Not ok: message sucessfully uploaded (I think when: "entry created in database" issue is fixed the message will be right).
