### ISSUE TITLE
Change font color

### ISSUE THREAD

**Issue by Simracer2018** [avs-code/PREM-Podium-race-E-manager#48]
How and where can I change the base color of the font [black] for the tool?

**Comment by avs-code** [comment]
What tool? attach a image if you can pointing to the thing that you want change.

**Comment by Simracer2018** [comment]
The Prem Tool. Championships, drivers, ect. create.
Here is a picture, the white font "6.season" is shown in black. I just maked a better view with the mouse. would like the font "6.season" in white font.
[](https://www.dropbox.com/s/8p5vbbomrdyw56p/Tool.PNG?dl=0)

**Comment by Simracer2018** [comment]
[https://www.dropbox.com/s/8p5vbbomrdyw56p/Tool.PNG?dl=0](url)

**Comment by avs-code** [comment]
You can do two things:

**1. Change the colour of the box:**
```php
<td width="120">Name:</td>
<td><div class="w3-white"> <?=$item['name']?></td>
```
or
**2. Change colour of the text**
```php
<td width="120">Name:</td>
<td><div class="w3-text-white"> <?=$item['name']?></td>
```
 *Example from file: division_chg.php line nº25

**Comment by Simracer2018** [comment]
Ok. Thanks !!!
