### ISSUE TITLE
Navbar Center?

### ISSUE THREAD

**Issue by Simracer2018** [avs-code/PREM-Podium-race-E-manager#49]
Hello, I have another question and how can I center the Nav Bar on the Prem Tools page.

**Comment by avs-code** [comment]
See the documentation, there are multiple options:
[https://www.w3schools.com/w3css/w3css_navigation.asp](url)

*nav.php

**Comment by avs-code** [comment]
what is your web page?

**Comment by Simracer2018** [comment]
Homepage: www.vvsr.de
Wertungstool: http://www.vvsr.de/auswertungen/

**Comment by avs-code** [comment]
Very cool, Great job really!

the only thing that, if you want, I would appreciate it if you put the word PREM with a link in the footer, in case someone likes PREM to know where to download the system. `Powered by **PREM** and revised by www.vvsr.de` you can do the same if you want with www.vvsr.de

This:
```php
Powered by <a href="https://arv187.github.io/PREM-Podium-race-E-manager" target="_blank">PREM</a> and revised by <a href="www.vvsr.de" target="_blank">www.vvsr.de</a>
```

Or similar thing.
