### ISSUE TITLE
Login area Font color change

### ISSUE THREAD

**Issue by Simracer2018** [avs-code/PREM-Podium-race-E-manager#52]
Hello again, there is still a question.
Where can I change the font color for Username and Password when I click on Login admin? Is currently black on our tool and would like to know.
Tool Link: http://www.vvsr.de/auswertungen
Greeting armin

**Comment by avs-code** [comment]
~~I can't find that option, the login form seems to be generated live via php function, does not use html or css, so I am not able to see how to do it. mysql_login.php~~

**Comment by avs-code** [comment]
**/prem/classes/mysql_login.php
Line 121 & 122**

```php
echo "<tr><td><div style ='background-color:black;color:white;'>$str_user:</div></td><td><input class=\"user\" type=\"text\" name=\"user\"></td></tr>\n";
echo "<tr><td><div style ='background-color:black;color:white;'>$str_pass:</div></td><td><input class=\"password\" type=\"password\" name=\"pass\"></td></tr>\n";
```


More info: https://www.w3schools.com/html/html_blocks.asp

**Comment by Simracer2018** [comment]
Thanks !!!!
