### ISSUE TITLE
Black Text to White Text

### ISSUE THREAD

**Issue by Simracer2018** [avs-code/PREM-Podium-race-E-manager#54]
Hello have found something else with us which is not to be seen in a background picture. If I want to delete a championship yes this is there:
"Division can not be deleted because it is related to the following season (s):"
• Seat Leon TRC
How do I get that in white instead of black as it is now.
In division_rem.php this says:
if (mysqli_num_rows ($ sresult)> 0) {
         $ seasons = "";
         while ($ s = mysqli_fetch_array ($ sresult)) {
                 $ seasons. = ".". $ s ['name']. "\ N";
         }
         show_error ("Division can not be deleted because it is related to the following season (s): \ n". $ seasons);
         return;
Greeting Armin

**Comment by avs-code** [comment]
On top of division_rem.php write this:
```php
<style>body {background-image: url("images/2011_FIA_GT1_Silverstone_2.jpg");}</style>
<div style ='background-color:black;color:white;'>
```

And on bottom of all code add this:

```php
</div>
```

**Comment by Simracer2018** [comment]
Thanks !!!!!!! The help here is really top !!!!
