### ISSUE TITLE
Standings Block errors when no standings exists.

### ISSUE THREAD

**Issue by rearley** [avs-code/PREM-Podium-race-E-manager#58]
**Describe the bug**
When loading a fresh copy of the database with no entries, this produces an error in the standings block. It is a PHP Notice but should not be there.

Notice: Undefined variable: standing_pages in /var/www/html/PREM-Podium-race-E-manager/blocks/standings.php on line 69

**To Reproduce**
1. Load fresh database
2. Enable PHP Errors
3. Navigate to main index.php page.

**Expected behavior**
You should just see an empty block or a message stating no standings found.

**Screenshots**
https://www.screencast.com/t/xBTZz5dEUULB

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 60.3.0esr (64-bit)

**Comment by avs-code** [comment]
Thanks! that block isn't finished, I'm not surprised that he has errors I going to upload a sql data to test in a new issue. #61
