### ISSUE TITLE
Join as a driver: You do not have administrator rights

### ISSUE THREAD

**Issue by avs-code** [avs-code/PREM-Podium-race-E-manager#7]
[ENG] So that the user can itself add her name and photo to the database has been backed driver_add_do.php calling driver_add_do_user.php and added this code:

```
<?php
define('USE_MYSQL', 1);
include 'functions.php';
include 'config.php';

$conn = mysql_connect($config['mysql']['host'], $config['mysql']['user'], $config['mysql']['pass'], $config['mysql']['db'])
or die('issues with the server connection');?>
```

It seems that the data are added correctly but the following warnings are displayed:

> Driver succesfully added
> You do not have administrator rights

It may be related to include 'functions.php'; o include 'config.php';

[ESP] Para que el usuario pueda por si mismo añadir su nombre y foto a la base de datos se ha hecho una copia de driver_add_do.php llamándola driver_add_do_user.php y se ha añadido este código:

```
<?php
define('USE_MYSQL', 1);
include 'functions.php';
include 'config.php';

$conn = mysql_connect($config['mysql']['host'], $config['mysql']['user'], $config['mysql']['pass'], $config['mysql']['db'])
or die('issues with the server connection');?>
```

Parece que los datos se añaden correctamente pero salen las siguientes advertencias:

> Driver succesfully added
> You do not have administrator rights

Puede estar relacionado con include 'functions.php'; o include 'config.php';

**Comment by inguni** [comment]
Resolved, was redirecting to an admin page, now it'll redirect to the correct page
